@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(customer, "Клиент банка", "Физическое лицо, интересующееся банковскими услугами или уже являющиеся клиентом банка")

System(banking_system, "Банковская система", "Обеспечивает информационное обслуживание, банковские операции и СМС-информирование для клиентов")

Rel(customer, banking_system, "Просматривает информацию о депозитах\nОставляет заявки на продукты\nУправляет счетами через личный кабинет\nПолучает СМС-уведомления")

@enduml