@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(customer, "Клиент банка", "Физическое или юридическое лицо, интересующееся банковскими услугами")

Person(call_center_agent, "Сотрудник кол-центра", "Внутренний сотрудник банка")

System(partner_call_center, "Партнерский кол-центр", "Внешняя система партнерского кол-центра")

System_Boundary(banking_system, "Банковская система") {
    Container(web_site, "Информационный сайт", "Веб-приложение", "Предоставляет информацию о депозитах, принимает заявки с ФИО, телефоном и выбранным продуктом")
    
    Container(internet_bank, "Интернет-клиент", "Веб-приложение", "Личный кабинет клиента для управления счетами и операциями")
    
    Container(back_office, "Бэк-офис", "Delphi приложение", "Интеграционный компонент между фронтенд-системами и АБС\nПредоставляет данные кол-центрам")
    
    Container(abs, "АБС", "Банковская система", "Автоматизированная банковская система - ядро обработки банковских продуктов\nОтправляет СМС-уведомления клиентам")
    
    ContainerDb(ik_db, "База данных ИК/ИС", "MS SQL Server", "Хранит данные сессий, заявки на депозиты, справочник продуктов")
    
    ContainerDb(abs_db, "База данных АБС", "Oracle Database", "Основная база данных банковских операций, клиентов и договоров")
    
    Container(file_export, "Файловый экспорт", "Файловая система", "Директория для выгрузки данных для партнерских кол-центров\nФорматы: CSV, XML")
}

' Взаимодействия с клиентом
Rel(customer, web_site, "Просматривает информацию\nОставляет заявки")
Rel(customer, internet_bank, "Управляет счетами\nВыполняет операции")
Rel(abs, customer, "Отправляет СМС-уведомления\nо решениях банка")

' Взаимодействия с кол-центрами
Rel(call_center_agent, back_office, "Просматривает данные о депозитах\nи статусы заявок")
Rel(back_office, file_export, "Выгружает данные для партнеров", "file")
Rel(partner_call_center, file_export, "Забирает файлы с данными", "file")

' Внутренние взаимодействия
Rel(web_site, internet_bank, "Передает заявки")
Rel(internet_bank, back_office, "Передает операции")
Rel(back_office, abs, "Создает договоры\nПередает операции")
Rel(abs, back_office, "Возвращает результаты")

' Взаимодействия с базами данных
Rel(web_site, ik_db, "Чтение продуктов\nЗапись заявок")
Rel(internet_bank, ik_db, "Управление данными")
Rel(abs, abs_db, "Обработка операций\nПолучение контактов для СМС")

' Обратная связь
Rel(back_office, internet_bank, "Возвращает статусы")
@enduml