@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(customer, "Клиент банка", "Физическое лицо, интересующееся банковскими услугами или уже являющиеся клиентом банка")

Person(call_center, "Сотрудник кол-центра", "Внутренний сотрудник кол-центра банка")

System(partner_call_center, "Партнерский кол-центр", "Внешняя система партнерского кол-центра")

System(banking_system, "Банковская система", "Обеспечивает информационное обслуживание, банковские операции и СМС-информирование для клиентов")

Rel(customer, banking_system, "Просматривает информацию о депозитах\nОставляет заявки на продукты\nУправляет счетами через личный кабинет\nПолучает СМС-уведомления")

Rel(call_center, banking_system, "Получает информацию о депозитах\nПросматривает статусы заявок\nКонсультирует клиентов")

Rel(partner_call_center, banking_system, "Получает данные о депозитах\nчерез файловый обмен", "file")

@enduml